### ISSUE TITLE
Blake3

### ISSUE THREAD

**Issue by dlandi** [NeuroXiq/Arctium#1]
Hello, I am very interested in your progress on Blake3. Let me know if you need any help.

**Comment by NeuroXiq** [comment]
> 
> 
> Hello, I am very interested in your progress on Blake3. Let me know if you need any help.

Hello, 
for now, I don't have too much free time to continue development, but in near future, I will try to finish BLAKE3 hash function (+ all others BLAKE3 algo's key gen, random gen etc.). Consider, that algorithm works for single block. Thank you for your concern.
